# vim: set fileencoding=utf-8
"""
rydnr/voicecloning/application/voice_cloning_app.py

This file defines the VoiceCloningApp class.

Copyright (C) 2023-today rydnr's https://github.com/rydnr/voice-cloning

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from pythoneda.shared.application import PythonEDA, enable
from rydnr.voicecloning.infrastructure.cli import VoiceCloningRequestedCli


@enable(VoiceCloningRequestedCli)
class VoiceCloningApp(PythonEDA):
    """
    Runs the VoiceCloningApp PythonEDA app.

    Class name: VoiceCloningApp

    Responsibilities:
        - Runs the VoiceCloning application.

    Collaborators:
        - Command-line handlers from rydnr.voicecloning.infrastructure.cli
    """

    def __init__(self):
        """
        Creates a new VoiceCloningApp instance.
        """
        # voicecloning_banner is automatically generated by
        # rydnr/voice-cloning nix's flake.
        try:
            from rydnr.voicecloning.application.nix_flake_to_graphviz_banner import (
                VoiceCloningAppBanner,
            )

            banner = VoiceCloningAppBanner()
        except ImportError:
            banner = None

        super().__init__(banner, __file__)


if __name__ == "__main__":
    asyncio.run(VoiceCloningApp.main())
